### PR TITLE
Add keybinding for selected tab operations

### PR DESCRIPTION
**Pull request by networm**
## Summary

Add keybinding for selected tab operations

## Tests

- [x] Chrome stable (macOS)
- [x] Firefox stable (macOS)
- [x] Chrome stable (Windows)
- [x] Firefox stable (Windows)

Optional:

- [ ] Chrome beta (macOS)
- [ ] Firefox beta (macOS)
- [ ] Chrome beta (Windows)
- [ ] Firefox beta (Windows)

### CODE REVIEW

**Review by edrex — APPROVED** [review]
I was just about to submit a patch for this when I noticed yours.

LGTM +1, tested in Chrome M100

@yorkxin PTAL

**Comment by yorkxin** [comment]
Sorry for late response. Looks good to me! I'll merge first and let you know when it's available on the stores.

**Comment by yorkxin** [comment]
It's been released to Chrome Web Store, Firefox Add-Ons and Microsoft Edge Extensions Store!

**Comment by networm** [comment]
Thank you.

**Pull request merged**
